---
- name: Check if Kubernetes is already running
  stat:
    path: /etc/kubernetes/manifests/etcd.yaml
  register: stat_result

- name: Initiate kubernetes
  shell: "kubeadm init --apiserver-advertise-address=172.28.128.10 --apiserver-cert-extra-sans=172.28.128.10  --node-name master-k8s"
  become: true
  when: stat_result.stat.exists == False

- name: Make .kube directory
  file:
    path: /home/vagrant/.kube
    state: directory

- name: Copy kubectl to home and make it executable
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    remote_src: True
  become: true

- name: Generate new kubeadm token
  shell: kubeadm token create

- name: Get kubeadm token
  shell: kubeadm token list | sed -n 2p | awk '{ print $1 };'
  register: kubeadm_token

- name: save token
  copy: content="{{  kubeadm_token.stdout  }}" dest="/home/vagrant/code/join_token"

- name: Apply weave
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: create clusterrolebinding permissions
  shell: "kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --user=admin --user=kubelet --group=system:serviceaccounts"

- name: Accept forward iptables
  shell: iptables -P FORWARD ACCEPT
  become: true
