#
# Copyright 2017 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: py-wordcount
  namespace: default
  lables: 
    release: prometheus-operator
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: 172.28.128.10/library/spark-prom:latest

  imagePullPolicy: Always
  dep:
    jars:
      - http://central.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.3.1/jmx_prometheus_javaagent-0.3.1.jar

  arguments:
    - "s3a://kubernetes/big.txt"
    - "s3a://kubernetes/output"



  hadoopConf:
    fs.s3a.endpoint: http://172.28.128.10:9000
    fs.s3a.access.key: AKIAIOSFODNN7EXAMPLE
    fs.s3a.secret.key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  mainApplicationFile: "s3a://kubernetes/word-count/wordcount.py"
  restartPolicy:
    type: Never

  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
      release: prometheus-operator
    serviceAccount: spark

  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.0
      release: prometheus-operator
 
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.3.1.jar"
      port: 8090 