---
- hosts: all
  become_method: sudo
  become: true
  roles:
    - dev
    - docker
    - install_k8s
    - network

- hosts: master-k8s
  become_method: sudo
  roles:
    - launch_k8s_master
    - helm
    - minio

- hosts:
    - node1-k8s
    - node2-k8s
  become_method: sudo
  roles:
    - join_k8s_cluster
