kind: Service
apiVersion: v1
metadata:
  name: spark-monitor-service
  namespace: spark-operator
  labels:
    spark-role: monitor
spec:
  selector:
    app.kubernetes.io/name: sparkoperator
  ports:
  - name: web
    port: 10254