---
- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Set iptables
  shell: "sysctl -w net.bridge.bridge-nf-call-iptables=1 && sysctl -w net.ipv4.ip_forward=1"
  become: true

- name: Copy iptables config for k8s
  copy:
    src: /vagrant/roles/network/files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: vagrant
    group: vagrant
    mode: 0444
  become: true

- name: implement ip tables as 1
  shell: "sysctl -p"
  become: true

- name: update hosts files
  shell: printf '172.28.128.10 master-k8s\n172.28.128.11 node1-k8s\n172.28.128.12 node2-k8s\n' >> /etc/hosts
