---
- name: Copy Kubernetes repo file
  copy:
    src: /vagrant/roles/install_k8s/files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: vagrant
    group: vagrant
    mode: 0444
  become: true

- name: Install Kubernetes Components
  yum:
    update_cache: yes
    name: "{{ item }}"
  with_items: "{{ kubernetes_packages }}"

- name: Turn swap off
  shell: "swapoff -a && sed -i '/ swap / s/^/#/' /etc/fstab"
  become: true

- name: Start and enable kubelet
  service:
    name: kubelet
    state: started
    enabled: true
