Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true

  config.vm.define "docker_registry" do |docker_registry|
    docker_registry.vm.box = "gugek/scientific-linux-7"
    docker_registry.vm.box_version = "7.2.0"
    docker_registry.vm.network "private_network", ip: "172.28.128.170"

    docker_registry.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end

    docker_registry.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "harbor-deployment.yml"
    end
  end
end
